name: html_components_polymer
version: 0.0.1
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library based on the Polymer.dart project.
homepage: http://html-components.appspot.com
environment:
  sdk: '>=0.6.13'
dependencies:
  animation: any
  js: any
  polymer: any
