name: html_components
version: 0.4.0
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library written in HTML and Dart using Polymer.dart.
homepage: https://github.com/szgabsz91/html-components
environment:
  sdk: ">=1.5.3"
dependencies:
  polymer: ">=0.11.0"
dev_dependencies:
  unittest: 0.10.1+2
  barback: ">=0.13.0"
transformers:
- polymer:
    entry_points:
    - example/index.html
- html_components/src/showcase_transformer