name: html_components
version: 0.0.1
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library written in HTML and Dart.
homepage: http://html-components.appspot.com
dependencies:
  animation: any
  browser: any
  js: any
  web_ui: any
