name: html_components
version: 0.1.0
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library written in HTML and Dart using Polymer.dart.
homepage: http://html-components.appspot.com
dependencies:
  animation: any
  polymer: any
  unittest: any
